### ISSUE TITLE
Which version of polymer is supported ?

### ISSUE THREAD

**Issue by yml** [microo8/golymer#3]
Hello,
I could not find out which version of polymer was supported by this project?
The [example is using 1.0.22](https://github.com/microo8/golymer/blob/master/examples/clock/index.html#L5)

If I am not mistaken version 3 is the latest: https://www.polymer-project.org/3.0/docs/about_30

Along the same line do you have any plan to support GOARCH=wasm (go 1.11) ?

Thank  you

**Comment by microo8** [comment]
The name is just clickbaity :tada: 
This isn't a wrapper around the polymer library. This is a library for html custom elements written from scratch in Go and compiled to javascript using `gophejs`.

In that [example](https://github.com/microo8/golymer/blob/master/examples/clock/index.html#L5) are used just the [polyfills](https://www.webcomponents.org/polyfills) (and not the polymer lib), because not all webbrowsers support custom elements.

`wasm` will not be supported. Creating custom elements from `wasm` will be an overkill. The lib would just have to call a lot of `js` functions and nothing meaningful in the `wasm` engine.

**Comment by ghost** [comment]
Yeah I was totally tricked and thought it used polymer too

**Comment by ghost** [comment]
Can't work out the code.
You have formal MD elements but don't see the full MD dependencies called MDC.

Maybe you should make a roadmap in the reader of you want people to use this and contribute ?

**Comment by ghost** [comment]
Ah I see some of the element already have the CSS embedded in your template object.
Where did you get the CSS from ?

Also how will you support RTL ? Not sure if it's CSS or mixed with a special layout template and some JavaScript magic.

It looks like a promising project though. I can see you don't want it 100% reliant on Google's MDC lib and actually I think it's wise. Why ? Because there are a ton of other widgets needs to make real apps. Data table , grids, calendaring, and others that just can't be easily made from their base widgets.

Anyway sorry about the stream of issues..do a roadmap and explanation of approach so others can see the why an help out

**Comment by microo8** [comment]
I think that the functionality is complete and working. The main interest would be to create other elements, like you mentioned, data table, grids, lists and so on.

But creating elements is for me a very hard work :) harder than making the entire library. css is not my friend :)
I've usually searched for some simple MD elements and copied the css from it. I used some css from the [mce](https://github.com/allenhwkim/mce) project.

Just thought that people would be excited by the project (also many have read the blog post) and would help out with making of new elements. But ~186 stars and no pull request :(

So maybe I try out creating a roadmap and some **"help needed"** section in readme would be nice.

**Comment by md9projeto** [comment]
There are a ton of GO groups both in Facebook,Linkedin,telegram,google
groups.If you leave a message in every place talking about your project
this can help.

2018-07-14 13:06 GMT-03:00 Vlαdo Magyar <notifications@github.com>:

**Comment by ghost** [comment]
CSS is hellish.

Why did you not just use the CSS from Google's MDC project ?

https://github.com/material-components/material-components-web-catalog



It's not designed for the Dom elements you use ?

**Comment by tokamak-git** [comment]
Hello, have been interested in this project for a while, and used the existing elements for some tests.
Question is "is it ready for production?" 
Have a project and would like to use golymer even though, Polymer and Ionic are established.
Moreover am open to writhing a guide about developing a business application, sadly there is not enough clarity around routing, ajax and authentication.
If anyone could point me in a direction, am ready to work on a starter kit, maybe even a https://www.polymer-project.org/3.0/start/toolbox/set-up like introduction, porting some of the polymer elements to golymer, especially the iron components. Is that a good idea?
Any and all code samples and direction is welcome. But then again is the project ready for production? is security a concern? ask only so as to make an informed decision about using golymer for a client.

**Comment by g5becks** [comment]
Just for the record, if having css scoped by shadow dom is not a main concern for you, then it might be helpful to know that you can actually <link> to stylesheets in  shadow dom. Knowing this was the one thing that removed the blockage from me using this awesome library, I didn't want to have to worry about making custom components,  https://stackoverflow.com/a/48202206/10117356 for more info. @raghuvanshy  routing, authentication, etc are separate concerns . I think this lib is simply great for the presentation layer though. A pretty good router is https://github.com/go-humble/router btw.
